### ISSUE TITLE
Excess newlines when adding items to an array

### ISSUE THREAD

**Issue by evertheylen** [evertheylen/silver-fleece#1]
Just like https://github.com/Rich-Harris/golden-fleece/issues/18

**Comment by manuel3108** [comment]
Are you willing to accept a PR for this? Still needs investigating and debugging, but i think i have found the root cause.

**Comment by evertheylen** [comment]
@manuel3108 sure! The project I was going to use this for was ... heavily delayed but recently I'm considering picking it back up. Although I'm considering to use https://github.com/microsoft/node-jsonc-parser

**Comment by manuel3108** [comment]
The project you mention seems to be overcomplicating things for us, so happy to continue using this 😆 

See #2 for the PR
